; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	__@@_PchSym_@00@UfhvihUqzpvaUwvhpglkUoryxzgrwUoryxzgrwRnzhgviUyfrowUnzgsUcGEUivovzhvUkivxlnkrovwOlyq@1E8B8899DC275176
;	COMDAT __@@_PchSym_@00@UfhvihUqzpvaUwvhpglkUoryxzgrwUoryxzgrwRnzhgviUyfrowUnzgsUcGEUivovzhvUkivxlnkrovwOlyq@1E8B8899DC275176
_BSS	SEGMENT
__@@_PchSym_@00@UfhvihUqzpvaUwvhpglkUoryxzgrwUoryxzgrwRnzhgviUyfrowUnzgsUcGEUivovzhvUkivxlnkrovwOlyq@1E8B8899DC275176 DD 01H DUP (?)
_BSS	ENDS
allocator_arg DB 01H DUP (?)
	ALIGN	4

piecewise_construct DB 01H DUP (?)
_BSS	ENDS
END
